services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    staticPublishPath: staticfiles
    autoDeploy: true
